<a href="https://colab.research.google.com/github/brianathrift/FINDCov19TrackerData/blob/master/scripts/data_processing/PPI/FIND_support_maps_scripts_05_17_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Updating FIND NGS support maps, while using NGS November underlying data

In [ ]:
#import packages
import pandas as pd
import seaborn as sns
import numpy as np

In [ ]:
#import November NGS map data (exported from github) 
github_url = "https://raw.githubusercontent.com/PandemicPreventionInstitute/ppi-output/main/ngs_find_map/find_map.csv"
df_NGS_findmap = pd.read_csv (github_url)
#drop first column "Unamed"
#df_NGS_findmap = df_NGS_findmap.iloc[0: , 1:]
df_NGS_findmap.head(3)

,geometry,code,country,population_size,world_bank_economies,cum_seq,date_tests_last_reported,days_since_tests_reported,tpr_year_smoothed_truncated,TPR_pct,...,ngs_facility,archetype_orig,dx_archetype,sx_archetype,sx_sequencing_rec,dx_testing_rec,prev_dx,prev_sequ,seq_but_no_test_flag,ngs_capacity_binary
0,"{""type"":""Polygon"",""coordinates"":[[[28.04511,9....",NaN,Abyei,NaN,Insufficient data,Insufficient data,Insufficient data,NaN,NaN,Insufficient data,...,Insufficient data,NaN,Insufficient testing data,Insufficient data,Insufficient data,Insufficient testing data,NaN,NaN,NaN,No
1,"{""type"":""Polygon"",""coordinates"":[[[27.825309,9...",NaN,Abyei Disputed Boundary,NaN,Insufficient data,Insufficient data,Insufficient data,NaN,NaN,Insufficient data,...,Insufficient data,NaN,Insufficient testing data,Insufficient data,Insufficient data,Insufficient testing data,NaN,NaN,NaN,No
2,"{""type"":""MultiPolygon"",""coordinates"":[[[[28.82...",NaN,Abyei Disputed Boundary,NaN,Insufficient data,Insufficient data,Insufficient data,NaN,NaN,Insufficient data,...,Insufficient data,NaN,Insufficient testing data,Insufficient data,Insufficient data,Insufficient testing data,NaN,NaN,NaN,No

In [ ]:
#import dataset that Swapna sent RE: FIND projects
FIND_github = "https://raw.githubusercontent.com/PandemicPreventionInstitute/NGS-Capacity-map/main/data/FIND_partner_support_maps/FIND_projects.csv"
df_FIND = pd.read_csv (FIND_github)
df_FIND.head()

,Country,Region,WB_eco,Archetype,N_projects,N_orgs
0,Cameroon,Africa,Lower middle income,Leverage,5,3
1,Brazil,Americas,Upper middle income,Strengthen,12,7
2,Guinea,Africa,Low income,Test,2,1
3,Lebanon,Eastern Mediterranean,Upper middle income,Leverage,3,1
4,Bangladesh,South-East Asia,Lower middle income,Strengthen,8,6

In [ ]:
#renaming and merging files
df_FIND.rename (columns = {'Country': 'country'}, inplace = True)
df_FIND.head(3)

    country    Region               WB_eco   Archetype  N_projects  N_orgs
0  Cameroon    Africa  Lower middle income    Leverage           5       3
1    Brazil  Americas  Upper middle income  Strengthen          12       7
2    Guinea    Africa           Low income        Test           2       1

In [ ]:
#merge together dataset
FIND_Projects_Flourish = df_NGS_findmap.merge(df_FIND, how = 'left', on = 'country')
FIND_Projects_Flourish.head(3)

,geometry,code,country,population_size,world_bank_economies,cum_seq,date_tests_last_reported,days_since_tests_reported,tpr_year_smoothed_truncated,TPR_pct,...,dx_testing_rec,prev_dx,prev_sequ,seq_but_no_test_flag,ngs_capacity_binary,Region,WB_eco,Archetype,N_projects,N_orgs
0,"{""type"":""Polygon"",""coordinates"":[[[28.04511,9....",NaN,Abyei,NaN,Insufficient data,Insufficient data,Insufficient data,NaN,NaN,Insufficient data,...,Insufficient testing data,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN
1,"{""type"":""Polygon"",""coordinates"":[[[27.825309,9...",NaN,Abyei Disputed Boundary,NaN,Insufficient data,Insufficient data,Insufficient data,NaN,NaN,Insufficient data,...,Insufficient testing data,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN
2,"{""type"":""MultiPolygon"",""coordinates"":[[[[28.82...",NaN,Abyei Disputed Boundary,NaN,Insufficient data,Insufficient data,Insufficient data,NaN,NaN,Insufficient data,...,Insufficient testing data,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN

In [ ]:
#confirm countrys have right # of projects reported
Cameroon_projects = FIND_Projects_Flourish.loc[(FIND_Projects_Flourish['country'] == 'Cameroon')]
Cameroon_projects.head(4)

,geometry,code,country,population_size,world_bank_economies,cum_seq,date_tests_last_reported,days_since_tests_reported,tpr_year_smoothed_truncated,TPR_pct,...,dx_testing_rec,prev_dx,prev_sequ,seq_but_no_test_flag,ngs_capacity_binary,Region,WB_eco,Archetype,N_projects,N_orgs
46,"{""type"":""Polygon"",""coordinates"":[[[16.189823,2...",CMR,Cameroon,26546000.0,Lower middle income,734,"April 19, 2022",12.0,0.0417,4.2 %,...,Test - Increase diagnostic testing capacity,Test,Strengthen/Leverage,no,Yes,Africa,Lower middle income,Leverage,5.0,3.0

In [ ]:
#confirm countrys have right # of projects reported
Brazil_projects = FIND_Projects_Flourish.loc[(FIND_Projects_Flourish['country'] == 'Brazil')]
Brazil_projects.head(4)

,geometry,code,country,population_size,world_bank_economies,cum_seq,date_tests_last_reported,days_since_tests_reported,tpr_year_smoothed_truncated,TPR_pct,...,dx_testing_rec,prev_dx,prev_sequ,seq_but_no_test_flag,ngs_capacity_binary,Region,WB_eco,Archetype,N_projects,N_orgs
38,"{""type"":""MultiPolygon"",""coordinates"":[[[[-58.1...",BRA,Brazil,212559000.0,Upper middle income,134497,"March 11, 2022",51.0,0.407,40.7 %,...,Test - Increase diagnostic testing capacity,Test,Sustain,yes,Yes,Americas,Upper middle income,Strengthen,12.0,7.0

In [ ]:
#confirm countrys have right # of projects reported
Ethiopia_projects = FIND_Projects_Flourish.loc[(FIND_Projects_Flourish['country'] == 'Ethiopia')]
Ethiopia_projects.head(4)

,geometry,code,country,population_size,world_bank_economies,cum_seq,date_tests_last_reported,days_since_tests_reported,tpr_year_smoothed_truncated,TPR_pct,...,dx_testing_rec,prev_dx,prev_sequ,seq_but_no_test_flag,ngs_capacity_binary,Region,WB_eco,Archetype,N_projects,N_orgs
79,"{""type"":""Polygon"",""coordinates"":[[[34.070698,9...",ETH,Ethiopia,114964000.0,Low income,616,"May 01, 2022",0.0,0.0973,9.7 %,...,Test - Increase diagnostic testing capacity,Test,Connect/Build,no,No,Africa,Low income,Connect,11.0,5.0

Adding lat/long to the df and make sure to only include variables of interests.

In [ ]:
#reading in github lat/long datafile
latlong_url = "https://gist.githubusercontent.com/tadast/8827699/raw/f5cac3d42d16b78348610fc4ec301e9234f82821/countries_codes_and_coordinates.csv"
lat_long_df = pd.read_csv(latlong_url)
lat_long_df.head()

,Country,Alpha-2 code,Alpha-3 code,Numeric code,Latitude (average),Longitude (average)
0,Afghanistan,"""AF""","""AFG""","""4""","""33""","""65"""
1,Albania,"""AL""","""ALB""","""8""","""41""","""20"""
2,Algeria,"""DZ""","""DZA""","""12""","""28""","""3"""
3,American Samoa,"""AS""","""ASM""","""16""","""-14.3333""","""-170"""
4,Andorra,"""AD""","""AND""","""20""","""42.5""","""1.6"""

In [ ]:
#replacing "" and changing data-type
lat_long_df = lat_long_df.replace('"','', regex=True)
lat_long_df.head()

,Country,Alpha-2 code,Alpha-3 code,Numeric code,Latitude (average),Longitude (average)
0,Afghanistan,AF,AFG,4,33,65
1,Albania,AL,ALB,8,41,20
2,Algeria,DZ,DZA,12,28,3
3,American Samoa,AS,ASM,16,-14.3333,-170
4,Andorra,AD,AND,20,42.5,1.6

In [ ]:
#change datatypes
lat_long_df["Alpha-3 code"] = lat_long_df["Alpha-3 code"].astype(str)
lat_long_df["Latitude (average)"] = lat_long_df["Latitude (average)"].astype(float)
lat_long_df["Longitude (average)"] = lat_long_df["Longitude (average)"].astype(float)
print (lat_long_df.dtypes)
lat_long_df.head()

Country                 object
Alpha-2 code            object
Alpha-3 code            object
Numeric code            object
Latitude (average)     float64
Longitude (average)    float64
dtype: object

,Country,Alpha-2 code,Alpha-3 code,Numeric code,Latitude (average),Longitude (average)
0,Afghanistan,AF,AFG,4,33.0000,65.0
1,Albania,AL,ALB,8,41.0000,20.0
2,Algeria,DZ,DZA,12,28.0000,3.0
3,American Samoa,AS,ASM,16,-14.3333,-170.0
4,Andorra,AD,AND,20,42.5000,1.6

In [ ]:
#rename variables
lat_long_df.rename (columns = {'Alpha-3 code': 'code'}, inplace = True)
lat_long_df.rename (columns = {'Latitude (average)': 'latitude'}, inplace = True)
lat_long_df.rename (columns = {'Longitude (average)': 'longitude'}, inplace = True)
lat_long_df.rename (columns = {'Country': 'country'}, inplace = True)
lat_long_df.head()

          country Alpha-2 code  code Numeric code  latitude  longitude
0     Afghanistan           AF   AFG            4   33.0000       65.0
1         Albania           AL   ALB            8   41.0000       20.0
2         Algeria           DZ   DZA           12   28.0000        3.0
3  American Samoa           AS   ASM           16  -14.3333     -170.0
4         Andorra           AD   AND           20   42.5000        1.6

In [ ]:
#only keeping necessary variables from this dataset, for our observations
lat_long_df = lat_long_df[['country', 'code', "latitude", 'longitude']]
lat_long_df.head()
print (lat_long_df.dtypes)

country       object
code          object
latitude     float64
longitude    float64
dtype: object

In [ ]:
FIND_Projects_Flourish.dtypes

geometry                                        object
code                                            object
country                                         object
population_size                                float64
world_bank_economies                            object
cum_seq                                         object
date_tests_last_reported                        object
days_since_tests_reported                      float64
tpr_year_smoothed_truncated                    float64
TPR_pct                                         object
avg_daily_tests_per_1000_last_year_smoothed    float64
daily_tests_per_1000                            object
pct_cases_sequenced_in_last_year                object
pct_seq                                         object
sequences_per_100k_last_year                    object
seq_per_100k                                    object
dx_testing_binary                               object
sars_cov_2_binary                               object
ngs_capacity                                   float64
facility_access                                 object
ngs_facility                                    object
archetype_orig                                  object
dx_archetype                                    object
sx_archetype                                    object
sx_sequencing_rec                               object
dx_testing_rec                                  object
prev_dx                                         object
prev_sequ                                       object
seq_but_no_test_flag                            object
ngs_capacity_binary                             object
Region                                          object
WB_eco                                          object
Archetype                                       object
N_projects                                     float64
N_orgs                                         float64
dtype: object

In [ ]:
FIND_df = FIND_Projects_Flourish[['geometry', 'code', "country", 'world_bank_economies', 'sx_archetype', 'dx_archetype', 
                                  'pct_seq', 'sequences_per_100k_last_year', 'TPR_pct', 'avg_daily_tests_per_1000_last_year_smoothed', 'N_projects', 'N_orgs' ]]

print (FIND_df.dtypes)
FIND_df.head()

geometry                                        object
code                                            object
country                                         object
world_bank_economies                            object
sx_archetype                                    object
dx_archetype                                    object
pct_seq                                         object
sequences_per_100k_last_year                    object
TPR_pct                                         object
avg_daily_tests_per_1000_last_year_smoothed    float64
N_projects                                     float64
N_orgs                                         float64
dtype: object

,geometry,code,country,world_bank_economies,sx_archetype,dx_archetype,pct_seq,sequences_per_100k_last_year,TPR_pct,avg_daily_tests_per_1000_last_year_smoothed,N_projects,N_orgs
0,"{""type"":""Polygon"",""coordinates"":[[[28.04511,9....",NaN,Abyei,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,NaN,NaN
1,"{""type"":""Polygon"",""coordinates"":[[[27.825309,9...",NaN,Abyei Disputed Boundary,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,NaN,NaN
2,"{""type"":""MultiPolygon"",""coordinates"":[[[[28.82...",NaN,Abyei Disputed Boundary,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,NaN,NaN
3,"{""type"":""Polygon"",""coordinates"":[[[28.328673,9...",NaN,Abyei Disputed Boundary,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,NaN,NaN
4,"{""type"":""Polygon"",""coordinates"":[[[74.892307,3...",AFG,Afghanistan,Low income,Connect/Build,Test,0.05 %,0.141,21.9 %,0.04,NaN,NaN

In [ ]:
#trying to round numbers...this did not work when there are NaN's
FIND_df[['N_projects','N_orgs']].astype(float).apply(np.round)
#FIND_df[['pct_seq','TPR_pct']].astype(float).apply(np.round)
#FIND_df[['sequences_per_100k_last_year','avg_daily_tests_per_1000_last_year_smoothed']].astype(float).apply(np.round)
FIND_df.head()

,geometry,code,country,world_bank_economies,sx_archetype,dx_archetype,pct_seq,sequences_per_100k_last_year,TPR_pct,avg_daily_tests_per_1000_last_year_smoothed,N_projects,N_orgs
0,"{""type"":""Polygon"",""coordinates"":[[[28.04511,9....",NaN,Abyei,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,NaN,NaN
1,"{""type"":""Polygon"",""coordinates"":[[[27.825309,9...",NaN,Abyei Disputed Boundary,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,NaN,NaN
2,"{""type"":""MultiPolygon"",""coordinates"":[[[[28.82...",NaN,Abyei Disputed Boundary,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,NaN,NaN
3,"{""type"":""Polygon"",""coordinates"":[[[28.328673,9...",NaN,Abyei Disputed Boundary,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,NaN,NaN
4,"{""type"":""Polygon"",""coordinates"":[[[74.892307,3...",AFG,Afghanistan,Low income,Connect/Build,Test,0.05 %,0.141,21.9 %,0.04,NaN,NaN

In [ ]:
#Confirm projects data is good
Projects_confirm = FIND_df.loc[(FIND_df['N_projects'] > 0)]
print ("N of countries w/projects:", Projects_confirm.country.nunique())
Projects_confirm.head()
#59 countries with projects

N of countries w/projects: 59

,geometry,code,country,world_bank_economies,sx_archetype,dx_archetype,pct_seq,sequences_per_100k_last_year,TPR_pct,avg_daily_tests_per_1000_last_year_smoothed,N_projects,N_orgs
15,"{""type"":""MultiPolygon"",""coordinates"":[[[[-68.4...",ARG,Argentina,Upper middle income,Strengthen/Leverage,Test,0.22 %,29.439,24.8 %,1.55,2.0,2.0
21,"{""type"":""MultiPolygon"",""coordinates"":[[[[158.8...",AUS,Australia,High income,Sustain,Sustain,1.31 %,302.983,11.3 %,5.63,1.0,1.0
27,"{""type"":""MultiPolygon"",""coordinates"":[[[[89.07...",BGD,Bangladesh,Lower middle income,Strengthen/Leverage,Test,0.33 %,2.395,14 %,0.14,8.0,6.0
28,"{""type"":""Polygon"",""coordinates"":[[[-59.42691,1...",BRB,Barbados,High income,Connect/Build,Sustain,0.14 %,31.977,13.3 %,4.71,1.0,1.0
35,"{""type"":""Polygon"",""coordinates"":[[[-67.193904,...",BOL,Bolivia,Lower middle income,Connect/Build,Sustain,0.02 %,1.073,16.3 %,0.65,1.0,1.0

In [ ]:
#merge together dataset
FIND_Regions_Points_Map = FIND_df.merge(lat_long_df, how = 'left', on = 'country')
FIND_Regions_Points_Map.head(3)

,geometry,code_x,country,world_bank_economies,sx_archetype,dx_archetype,pct_seq,sequences_per_100k_last_year,TPR_pct,avg_daily_tests_per_1000_last_year_smoothed,N_projects,N_orgs,code_y,latitude,longitude
0,"{""type"":""Polygon"",""coordinates"":[[[28.04511,9....",NaN,Abyei,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,NaN,NaN,NaN,NaN,NaN
1,"{""type"":""Polygon"",""coordinates"":[[[27.825309,9...",NaN,Abyei Disputed Boundary,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,NaN,NaN,NaN,NaN,NaN
2,"{""type"":""MultiPolygon"",""coordinates"":[[[[28.82...",NaN,Abyei Disputed Boundary,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
print (FIND_Regions_Points_Map.shape)
print (FIND_df.shape)

(286, 15)
(286, 12)

In [ ]:
url = 'https://raw.githubusercontent.com/PandemicPreventionInstitute/NGS-Capacity-map/main/data/FIND_partner_support_maps/FIND_df_metadata.csv'
FIND_metadata = pd.read_csv (url)
FIND_metadata.head()

,country,access_tools,workforce_strength,enchance_data,max_connect,future_emerg
0,All,4,6,7,1,0
1,Africa,1,2,1,0,1
2,Cameroon,1,3,2,0,0
3,Brazil,6,9,8,5,5
4,Guinea,0,2,0,0,0

In [ ]:
#merge together dataset
FIND_Projects_Org_Map = FIND_Regions_Points_Map.merge(FIND_metadata, how = 'left', on = 'country')
FIND_Projects_Org_Map.head(3)

,geometry,code_x,country,world_bank_economies,sx_archetype,dx_archetype,pct_seq,sequences_per_100k_last_year,TPR_pct,avg_daily_tests_per_1000_last_year_smoothed,N_projects,N_orgs,code_y,latitude,longitude,access_tools,workforce_strength,enchance_data,max_connect,future_emerg
0,"{""type"":""Polygon"",""coordinates"":[[[28.04511,9....",NaN,Abyei,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"{""type"":""Polygon"",""coordinates"":[[[27.825309,9...",NaN,Abyei Disputed Boundary,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"{""type"":""MultiPolygon"",""coordinates"":[[[[28.82...",NaN,Abyei Disputed Boundary,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Explore Cameroon data
Cam_data = FIND_Projects_Org_Map.loc[(FIND_Projects_Org_Map['country'] == 'Cameroon')]
Cam_data.head()

,geometry,code_x,country,world_bank_economies,sx_archetype,dx_archetype,pct_seq,sequences_per_100k_last_year,TPR_pct,avg_daily_tests_per_1000_last_year_smoothed,N_projects,N_orgs,code_y,latitude,longitude,access_tools,workforce_strength,enchance_data,max_connect,future_emerg
46,"{""type"":""Polygon"",""coordinates"":[[[16.189823,2...",CMR,Cameroon,Lower middle income,Strengthen/Leverage,Test,0.94 %,1.649,4.2 %,0.13,5.0,3.0,CMR,6.0,12.0,1.0,3.0,2.0,0.0,0.0

In [ ]:
FIND_Projects_Org_Map.dtypes
FIND_Projects_Org_Map["access_tools"] = FIND_Projects_Org_Map["access_tools"].astype(float)
FIND_Projects_Org_Map["workforce_strength"] = FIND_Projects_Org_Map["workforce_strength"].astype(float)
FIND_Projects_Org_Map["enchance_data"] = FIND_Projects_Org_Map["enchance_data"].astype(float)
FIND_Projects_Org_Map["max_connect"] = FIND_Projects_Org_Map["max_connect"].astype(float)
FIND_Projects_Org_Map["future_emerg"] = FIND_Projects_Org_Map["future_emerg"].astype(float)
FIND_Projects_Org_Map.dtypes

geometry                                        object
code_x                                          object
country                                         object
world_bank_economies                            object
sx_archetype                                    object
dx_archetype                                    object
pct_seq                                         object
sequences_per_100k_last_year                    object
TPR_pct                                         object
avg_daily_tests_per_1000_last_year_smoothed    float64
N_projects                                     float64
N_orgs                                         float64
code_y                                          object
latitude                                       float64
longitude                                      float64
access_tools                                   float64
workforce_strength                             float64
enchance_data                                  float64
max_connect                                    float64
future_emerg                                   float64
dtype: object

In [ ]:
def num (x):
    if x > 0:
        return '✓' 
    elif x <= 0:
        return 'X'
    else:
        return 'X'
    
FIND_Projects_Org_Map['access_tools'] = FIND_Projects_Org_Map['access_tools'].apply(lambda x : num (x))
FIND_Projects_Org_Map['workforce_strength'] = FIND_Projects_Org_Map['workforce_strength'].apply(lambda x : num (x))
FIND_Projects_Org_Map['enchance_data'] = FIND_Projects_Org_Map['enchance_data'].apply(lambda x : num (x))
FIND_Projects_Org_Map['max_connect'] = FIND_Projects_Org_Map['max_connect'].apply(lambda x : num (x))
FIND_Projects_Org_Map['future_emerg'] = FIND_Projects_Org_Map['future_emerg'].apply(lambda x : num (x))
FIND_Projects_Org_Map.head(2)

,geometry,code_x,country,world_bank_economies,sx_archetype,dx_archetype,pct_seq,sequences_per_100k_last_year,TPR_pct,avg_daily_tests_per_1000_last_year_smoothed,N_projects,N_orgs,code_y,latitude,longitude,access_tools,workforce_strength,enchance_data,max_connect,future_emerg
0,"{""type"":""Polygon"",""coordinates"":[[[28.04511,9....",NaN,Abyei,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,NaN,NaN,NaN,NaN,NaN,X,X,X,X,X
1,"{""type"":""Polygon"",""coordinates"":[[[27.825309,9...",NaN,Abyei Disputed Boundary,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,NaN,NaN,NaN,NaN,NaN,X,X,X,X,X

In [ ]:
#make high income and LMIC dfs

#High Income df
HIC_df = FIND_Projects_Org_Map.loc[(FIND_Projects_Org_Map['world_bank_economies'] == 'High income')]
HIC_df.head()

#LMIC df
LMIC_df = FIND_Projects_Org_Map.loc[(FIND_Projects_Org_Map['world_bank_economies'] != 'High income')]
LMIC_df.head()

,geometry,code_x,country,world_bank_economies,sx_archetype,dx_archetype,pct_seq,sequences_per_100k_last_year,TPR_pct,avg_daily_tests_per_1000_last_year_smoothed,N_projects,N_orgs,code_y,latitude,longitude,access_tools,workforce_strength,enchance_data,max_connect,future_emerg
0,"{""type"":""Polygon"",""coordinates"":[[[28.04511,9....",NaN,Abyei,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,NaN,NaN,NaN,NaN,NaN,X,X,X,X,X
1,"{""type"":""Polygon"",""coordinates"":[[[27.825309,9...",NaN,Abyei Disputed Boundary,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,NaN,NaN,NaN,NaN,NaN,X,X,X,X,X
2,"{""type"":""MultiPolygon"",""coordinates"":[[[[28.82...",NaN,Abyei Disputed Boundary,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,NaN,NaN,NaN,NaN,NaN,X,X,X,X,X
3,"{""type"":""Polygon"",""coordinates"":[[[28.328673,9...",NaN,Abyei Disputed Boundary,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,NaN,NaN,NaN,NaN,NaN,X,X,X,X,X
4,"{""type"":""Polygon"",""coordinates"":[[[74.892307,3...",AFG,Afghanistan,Low income,Connect/Build,Test,0.05 %,0.141,21.9 %,0.04,NaN,NaN,AFG,33.0,65.0,X,X,X,X,X

In [ ]:
print (HIC_df.shape)
HIC_df.head()

(82, 20)

,geometry,code_x,country,world_bank_economies,sx_archetype,dx_archetype,pct_seq,sequences_per_100k_last_year,TPR_pct,avg_daily_tests_per_1000_last_year_smoothed,N_projects,N_orgs,code_y,latitude,longitude,access_tools,workforce_strength,enchance_data,max_connect,future_emerg
11,"{""type"":""Polygon"",""coordinates"":[[[1.429297,42...",AND,Andorra,High income,Sustain,Test,0.66 %,240.453,21 %,5.03,NaN,NaN,AND,42.5000,1.6000,X,X,X,X,X
14,"{""type"":""MultiPolygon"",""coordinates"":[[[[-61.8...",ATG,Antigua and Barbuda,High income,Sustain,Insufficient data,2.64 %,171.177,2.6 %,0.35,NaN,NaN,ATG,17.0500,-61.8000,X,X,X,X,X
17,"{""type"":""Polygon"",""coordinates"":[[[-69.996938,...",ABW,Aruba,High income,Sustain,Insufficient data,9.37 %,2114.837,Insufficient data,NaN,NaN,NaN,ABW,12.5000,-69.9667,X,X,X,X,X
21,"{""type"":""MultiPolygon"",""coordinates"":[[[[158.8...",AUS,Australia,High income,Sustain,Sustain,1.31 %,302.983,11.3 %,5.63,1.0,1.0,AUS,-27.0000,133.0000,X,X,✓,X,X
24,"{""type"":""Polygon"",""coordinates"":[[[13.815725,4...",AUT,Austria,High income,Sustain,Sustain,2.1 %,817.996,2.3 %,45.99,NaN,NaN,AUT,47.3333,13.3333,X,X,X,X,X

In [ ]:
def num (x):
    if x == "✓":
        return 'HIC receiving partner support' 
    elif x == "X":
        return 'HIC not receiving partner support'
    else:
        return "HIC not receiving partner support"

#Delineate HIC and LMIC support...    
HIC_df['access_tools_support'] = HIC_df['access_tools'].apply(lambda x : num (x))
HIC_df['workforce_strength_support'] = HIC_df['workforce_strength'].apply(lambda x : num (x))
HIC_df['enchance_data_support'] = HIC_df['enchance_data'].apply(lambda x : num (x))
HIC_df['max_connect_support'] = HIC_df['max_connect'].apply(lambda x : num (x))
HIC_df['future_emerg_support'] = HIC_df['future_emerg'].apply(lambda x : num (x))
HIC_df.head(2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,geometry,code_x,country,world_bank_economies,sx_archetype,dx_archetype,pct_seq,sequences_per_100k_last_year,TPR_pct,avg_daily_tests_per_1000_last_year_smoothed,...,access_tools,workforce_strength,enchance_data,max_connect,future_emerg,access_tools_support,workforce_strength_support,enchance_data_support,max_connect_support,future_emerg_support
11,"{""type"":""Polygon"",""coordinates"":[[[1.429297,42...",AND,Andorra,High income,Sustain,Test,0.66 %,240.453,21 %,5.03,...,X,X,X,X,X,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support
14,"{""type"":""MultiPolygon"",""coordinates"":[[[[-61.8...",ATG,Antigua and Barbuda,High income,Sustain,Insufficient data,2.64 %,171.177,2.6 %,0.35,...,X,X,X,X,X,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support

In [ ]:
#Fill in NAN values with 0
# NOTE: make sure to have NaN available for "Point" map, where you do not want 0's popping up for all countries
HIC_df['N_projects'] = HIC_df ['N_projects'].replace(np.inf, np.nan)
HIC_df['N_projects'].fillna(0, inplace = True)
HIC_df["N_projects"] = HIC_df["N_projects"].astype(int)

#filling in NaN with 0's for organization metric as well
HIC_df['N_orgs'] = HIC_df ['N_orgs'].replace(np.inf, np.nan)
HIC_df['N_orgs'].fillna(0, inplace = True)
HIC_df["N_orgs"] = HIC_df["N_orgs"].astype(int)

#confirming all reported metrics are integers and reviewing head of df
print (HIC_df.dtypes)
HIC_df.head(3)

geometry                                        object
code_x                                          object
country                                         object
world_bank_economies                            object
sx_archetype                                    object
dx_archetype                                    object
pct_seq                                         object
sequences_per_100k_last_year                    object
TPR_pct                                         object
avg_daily_tests_per_1000_last_year_smoothed    float64
N_projects                                       int64
N_orgs                                           int64
code_y                                          object
latitude                                       float64
longitude                                      float64
access_tools                                    object
workforce_strength                              object
enchance_data                                   object
max_connect                                     object
future_emerg                                    object
access_tools_support                            object
workforce_strength_support                      object
enchance_data_support                           object
max_connect_support                             object
future_emerg_support                            object
dtype: object

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6392: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

,geometry,code_x,country,world_bank_economies,sx_archetype,dx_archetype,pct_seq,sequences_per_100k_last_year,TPR_pct,avg_daily_tests_per_1000_last_year_smoothed,...,access_tools,workforce_strength,enchance_data,max_connect,future_emerg,access_tools_support,workforce_strength_support,enchance_data_support,max_connect_support,future_emerg_support
11,"{""type"":""Polygon"",""coordinates"":[[[1.429297,42...",AND,Andorra,High income,Sustain,Test,0.66 %,240.453,21 %,5.03,...,X,X,X,X,X,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support
14,"{""type"":""MultiPolygon"",""coordinates"":[[[[-61.8...",ATG,Antigua and Barbuda,High income,Sustain,Insufficient data,2.64 %,171.177,2.6 %,0.35,...,X,X,X,X,X,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support
17,"{""type"":""Polygon"",""coordinates"":[[[-69.996938,...",ABW,Aruba,High income,Sustain,Insufficient data,9.37 %,2114.837,Insufficient data,NaN,...,X,X,X,X,X,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support

In [ ]:
def num (x):
    if x == 0:
        return 0 #Yes
    elif x > 0:
        return 1 #No

HIC_df['Projects_Funded'] = HIC_df['N_projects'].apply(lambda x : num (x))
HIC_df.head(3)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

,geometry,code_x,country,world_bank_economies,sx_archetype,dx_archetype,pct_seq,sequences_per_100k_last_year,TPR_pct,avg_daily_tests_per_1000_last_year_smoothed,...,workforce_strength,enchance_data,max_connect,future_emerg,access_tools_support,workforce_strength_support,enchance_data_support,max_connect_support,future_emerg_support,Projects_Funded
11,"{""type"":""Polygon"",""coordinates"":[[[1.429297,42...",AND,Andorra,High income,Sustain,Test,0.66 %,240.453,21 %,5.03,...,X,X,X,X,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,0
14,"{""type"":""MultiPolygon"",""coordinates"":[[[[-61.8...",ATG,Antigua and Barbuda,High income,Sustain,Insufficient data,2.64 %,171.177,2.6 %,0.35,...,X,X,X,X,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,0
17,"{""type"":""Polygon"",""coordinates"":[[[-69.996938,...",ABW,Aruba,High income,Sustain,Insufficient data,9.37 %,2114.837,Insufficient data,NaN,...,X,X,X,X,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,0

In [ ]:
#Fill in NAN values with 0
HIC_df['Projects_Funded'] = HIC_df ['Projects_Funded'].replace(np.inf, np.nan)
HIC_df['Projects_Funded'].fillna(0, inplace = True)
HIC_df["Projects_Funded"] = HIC_df["Projects_Funded"].astype(int)
print (HIC_df.dtypes)
HIC_df.head()

geometry                                        object
code_x                                          object
country                                         object
world_bank_economies                            object
sx_archetype                                    object
dx_archetype                                    object
pct_seq                                         object
sequences_per_100k_last_year                    object
TPR_pct                                         object
avg_daily_tests_per_1000_last_year_smoothed    float64
N_projects                                       int64
N_orgs                                           int64
code_y                                          object
latitude                                       float64
longitude                                      float64
access_tools                                    object
workforce_strength                              object
enchance_data                                   object
max_connect                                     object
future_emerg                                    object
access_tools_support                            object
workforce_strength_support                      object
enchance_data_support                           object
max_connect_support                             object
future_emerg_support                            object
Projects_Funded                                  int64
dtype: object

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6392: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

,geometry,code_x,country,world_bank_economies,sx_archetype,dx_archetype,pct_seq,sequences_per_100k_last_year,TPR_pct,avg_daily_tests_per_1000_last_year_smoothed,...,workforce_strength,enchance_data,max_connect,future_emerg,access_tools_support,workforce_strength_support,enchance_data_support,max_connect_support,future_emerg_support,Projects_Funded
11,"{""type"":""Polygon"",""coordinates"":[[[1.429297,42...",AND,Andorra,High income,Sustain,Test,0.66 %,240.453,21 %,5.03,...,X,X,X,X,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,0
14,"{""type"":""MultiPolygon"",""coordinates"":[[[[-61.8...",ATG,Antigua and Barbuda,High income,Sustain,Insufficient data,2.64 %,171.177,2.6 %,0.35,...,X,X,X,X,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,0
17,"{""type"":""Polygon"",""coordinates"":[[[-69.996938,...",ABW,Aruba,High income,Sustain,Insufficient data,9.37 %,2114.837,Insufficient data,NaN,...,X,X,X,X,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,0
21,"{""type"":""MultiPolygon"",""coordinates"":[[[[158.8...",AUS,Australia,High income,Sustain,Sustain,1.31 %,302.983,11.3 %,5.63,...,X,✓,X,X,HIC not receiving partner support,HIC not receiving partner support,HIC receiving partner support,HIC not receiving partner support,HIC not receiving partner support,1
24,"{""type"":""Polygon"",""coordinates"":[[[13.815725,4...",AUT,Austria,High income,Sustain,Sustain,2.1 %,817.996,2.3 %,45.99,...,X,X,X,X,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,0

In [ ]:
def num (x):
    if x == 0.0: #No projects
        return "HIC not receiving partner support"
    elif x == 1.0: #Yes, projects
        return "HIC receiving partner support"

HIC_df['support'] = HIC_df['Projects_Funded'].apply(lambda x : num (x))
HIC_df.head(3)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

,geometry,code_x,country,world_bank_economies,sx_archetype,dx_archetype,pct_seq,sequences_per_100k_last_year,TPR_pct,avg_daily_tests_per_1000_last_year_smoothed,...,enchance_data,max_connect,future_emerg,access_tools_support,workforce_strength_support,enchance_data_support,max_connect_support,future_emerg_support,Projects_Funded,support
11,"{""type"":""Polygon"",""coordinates"":[[[1.429297,42...",AND,Andorra,High income,Sustain,Test,0.66 %,240.453,21 %,5.03,...,X,X,X,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,0,HIC not receiving partner support
14,"{""type"":""MultiPolygon"",""coordinates"":[[[[-61.8...",ATG,Antigua and Barbuda,High income,Sustain,Insufficient data,2.64 %,171.177,2.6 %,0.35,...,X,X,X,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,0,HIC not receiving partner support
17,"{""type"":""Polygon"",""coordinates"":[[[-69.996938,...",ABW,Aruba,High income,Sustain,Insufficient data,9.37 %,2114.837,Insufficient data,NaN,...,X,X,X,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,HIC not receiving partner support,0,HIC not receiving partner support

Data Processing and Tranformation of LMICs df

In [ ]:
def num (x):
    if x == "✓":
        return 'LMIC receiving partner support' 
    elif x == "X":
        return 'LMIC not receiving partner support'
    else:
        return 'LMIC not receiving partner support'

#Delineate HIC and LMIC support...    
LMIC_df['access_tools_support'] = LMIC_df['access_tools'].apply(lambda x : num (x))
LMIC_df['workforce_strength_support'] = LMIC_df['workforce_strength'].apply(lambda x : num (x))
LMIC_df['enchance_data_support'] = LMIC_df['enchance_data'].apply(lambda x : num (x))
LMIC_df['max_connect_support'] = LMIC_df['max_connect'].apply(lambda x : num (x))
LMIC_df['future_emerg_support'] = LMIC_df['future_emerg'].apply(lambda x : num (x))
LMIC_df.head(2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,geometry,code_x,country,world_bank_economies,sx_archetype,dx_archetype,pct_seq,sequences_per_100k_last_year,TPR_pct,avg_daily_tests_per_1000_last_year_smoothed,...,access_tools,workforce_strength,enchance_data,max_connect,future_emerg,access_tools_support,workforce_strength_support,enchance_data_support,max_connect_support,future_emerg_support
0,"{""type"":""Polygon"",""coordinates"":[[[28.04511,9....",NaN,Abyei,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,...,X,X,X,X,X,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support
1,"{""type"":""Polygon"",""coordinates"":[[[27.825309,9...",NaN,Abyei Disputed Boundary,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,...,X,X,X,X,X,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support

In [ ]:
#Fill in NAN values with 0
# NOTE: make sure to have NaN available for "Point" map, where you do not want 0's popping up for all countries
LMIC_df['N_projects'] = LMIC_df ['N_projects'].replace(np.inf, np.nan)
LMIC_df['N_projects'].fillna(0, inplace = True)
LMIC_df["N_projects"] = LMIC_df["N_projects"].astype(int)

#filling in NaN with 0's for organization metric as well
LMIC_df['N_orgs'] = LMIC_df ['N_orgs'].replace(np.inf, np.nan)
LMIC_df['N_orgs'].fillna(0, inplace = True)
LMIC_df["N_orgs"] = LMIC_df["N_orgs"].astype(int)

#confirming all reported metrics are integers and reviewing head of df
print (LMIC_df.dtypes)
LMIC_df.head(3)

geometry                                        object
code_x                                          object
country                                         object
world_bank_economies                            object
sx_archetype                                    object
dx_archetype                                    object
pct_seq                                         object
sequences_per_100k_last_year                    object
TPR_pct                                         object
avg_daily_tests_per_1000_last_year_smoothed    float64
N_projects                                       int64
N_orgs                                           int64
code_y                                          object
latitude                                       float64
longitude                                      float64
access_tools                                    object
workforce_strength                              object
enchance_data                                   object
max_connect                                     object
future_emerg                                    object
access_tools_support                            object
workforce_strength_support                      object
enchance_data_support                           object
max_connect_support                             object
future_emerg_support                            object
dtype: object

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6392: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

,geometry,code_x,country,world_bank_economies,sx_archetype,dx_archetype,pct_seq,sequences_per_100k_last_year,TPR_pct,avg_daily_tests_per_1000_last_year_smoothed,...,access_tools,workforce_strength,enchance_data,max_connect,future_emerg,access_tools_support,workforce_strength_support,enchance_data_support,max_connect_support,future_emerg_support
0,"{""type"":""Polygon"",""coordinates"":[[[28.04511,9....",NaN,Abyei,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,...,X,X,X,X,X,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support
1,"{""type"":""Polygon"",""coordinates"":[[[27.825309,9...",NaN,Abyei Disputed Boundary,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,...,X,X,X,X,X,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support
2,"{""type"":""MultiPolygon"",""coordinates"":[[[[28.82...",NaN,Abyei Disputed Boundary,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,...,X,X,X,X,X,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support

In [ ]:
def num (x):
    if x == 0:
        return 0 #Yes, projects
    elif x > 0:
        return 1 #No, projects

LMIC_df['Projects_Funded'] = LMIC_df['N_projects'].apply(lambda x : num (x))
LMIC_df.head(3)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

,geometry,code_x,country,world_bank_economies,sx_archetype,dx_archetype,pct_seq,sequences_per_100k_last_year,TPR_pct,avg_daily_tests_per_1000_last_year_smoothed,...,workforce_strength,enchance_data,max_connect,future_emerg,access_tools_support,workforce_strength_support,enchance_data_support,max_connect_support,future_emerg_support,Projects_Funded
0,"{""type"":""Polygon"",""coordinates"":[[[28.04511,9....",NaN,Abyei,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,...,X,X,X,X,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,0
1,"{""type"":""Polygon"",""coordinates"":[[[27.825309,9...",NaN,Abyei Disputed Boundary,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,...,X,X,X,X,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,0
2,"{""type"":""MultiPolygon"",""coordinates"":[[[[28.82...",NaN,Abyei Disputed Boundary,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,...,X,X,X,X,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,0

In [ ]:
def num (x):
    if x == 0.0:
        return "LMIC not receiving partner support"
    elif x == 1.0:
        return "LMIC receiving partner support"

LMIC_df['support'] = LMIC_df['Projects_Funded'].apply(lambda x : num (x))
LMIC_df.head(3)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

,geometry,code_x,country,world_bank_economies,sx_archetype,dx_archetype,pct_seq,sequences_per_100k_last_year,TPR_pct,avg_daily_tests_per_1000_last_year_smoothed,...,enchance_data,max_connect,future_emerg,access_tools_support,workforce_strength_support,enchance_data_support,max_connect_support,future_emerg_support,Projects_Funded,support
0,"{""type"":""Polygon"",""coordinates"":[[[28.04511,9....",NaN,Abyei,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,...,X,X,X,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,0,LMIC not receiving partner support
1,"{""type"":""Polygon"",""coordinates"":[[[27.825309,9...",NaN,Abyei Disputed Boundary,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,...,X,X,X,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,0,LMIC not receiving partner support
2,"{""type"":""MultiPolygon"",""coordinates"":[[[[28.82...",NaN,Abyei Disputed Boundary,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,...,X,X,X,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,0,LMIC not receiving partner support

Confirm df's are correct by testing country: Cameroon

In [ ]:
#Exploring Cameroon to make sure this data makes sense
Cameroon_final_df = LMIC_df.loc[(LMIC_df['country'] == 'Cameroon')]
Cameroon_final_df.head()

,geometry,code_x,country,world_bank_economies,sx_archetype,dx_archetype,pct_seq,sequences_per_100k_last_year,TPR_pct,avg_daily_tests_per_1000_last_year_smoothed,...,enchance_data,max_connect,future_emerg,access_tools_support,workforce_strength_support,enchance_data_support,max_connect_support,future_emerg_support,Projects_Funded,support
46,"{""type"":""Polygon"",""coordinates"":[[[16.189823,2...",CMR,Cameroon,Lower middle income,Strengthen/Leverage,Test,0.94 %,1.649,4.2 %,0.13,...,✓,X,X,LMIC receiving partner support,LMIC receiving partner support,LMIC receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,1,LMIC receiving partner support

In [ ]:
#Exploring Sudan to make sure this data makes sense
Sudan_final_df = LMIC_df.loc[(LMIC_df['country'] == 'Sudan')]
Sudan_final_df.head()

,geometry,code_x,country,world_bank_economies,sx_archetype,dx_archetype,pct_seq,sequences_per_100k_last_year,TPR_pct,avg_daily_tests_per_1000_last_year_smoothed,...,enchance_data,max_connect,future_emerg,access_tools_support,workforce_strength_support,enchance_data_support,max_connect_support,future_emerg_support,Projects_Funded,support
235,"{""type"":""MultiPolygon"",""coordinates"":[[[[31.49...",SDN,Sudan,Low income,Connect/Build,Insufficient data,0.05 %,0.029,2.1 %,0.04,...,✓,X,X,LMIC not receiving partner support,LMIC receiving partner support,LMIC receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,1,LMIC receiving partner support

In [ ]:
#Exploring Sudan to make sure this data makes sense
Algeria_final_df = LMIC_df.loc[(LMIC_df['country'] == 'Algeria')]
Algeria_final_df.head()

,geometry,code_x,country,world_bank_economies,sx_archetype,dx_archetype,pct_seq,sequences_per_100k_last_year,TPR_pct,avg_daily_tests_per_1000_last_year_smoothed,...,enchance_data,max_connect,future_emerg,access_tools_support,workforce_strength_support,enchance_data_support,max_connect_support,future_emerg_support,Projects_Funded,support
9,"{""type"":""Polygon"",""coordinates"":[[[-8.681222,2...",DZA,Algeria,Lower middle income,Connect/Build,Insufficient data,0.13 %,0.428,Insufficient data,NaN,...,X,X,X,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,0,LMIC not receiving partner support

Concatenate HIC & LMICs together to make the joined/final df for the FIND partner maps

In [ ]:
#Concat the df's to stack them
# concatenating df1 and df2 along rows
FIND_partner_maps = pd.concat([HIC_df, LMIC_df], axis=0)
FIND_partner_maps.tail()

,geometry,code_x,country,world_bank_economies,sx_archetype,dx_archetype,pct_seq,sequences_per_100k_last_year,TPR_pct,avg_daily_tests_per_1000_last_year_smoothed,...,enchance_data,max_connect,future_emerg,access_tools_support,workforce_strength_support,enchance_data_support,max_connect_support,future_emerg_support,Projects_Funded,support
281,"{""type"":""MultiPolygon"",""coordinates"":[[[[-10.6...",ESH,Western Sahara,No income data,Insufficient data,Insufficient data,Insufficient data,Insufficient data,No cases reported,0.03,...,X,X,X,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,0,LMIC not receiving partner support
282,"{""type"":""MultiPolygon"",""coordinates"":[[[[-11.0...",NaN,Western Sahara - Morocco Disputed Boundary,Insufficient data,Insufficient data,Insufficient testing data,Insufficient data,Insufficient data,Insufficient data,NaN,...,X,X,X,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,0,LMIC not receiving partner support
283,"{""type"":""MultiPolygon"",""coordinates"":[[[[51.97...",YEM,Yemen,Low income,Connect/Build,Insufficient data,0 %,0,Insufficient data,NaN,...,X,X,X,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,0,LMIC not receiving partner support
284,"{""type"":""Polygon"",""coordinates"":[[[32.920863,-...",ZMB,Zambia,Lower middle income,Strengthen/Leverage,Test,0.29 %,3.509,11.2 %,0.30,...,✓,X,X,LMIC receiving partner support,LMIC receiving partner support,LMIC receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,1,LMIC receiving partner support
285,"{""type"":""Polygon"",""coordinates"":[[[31.288922,-...",ZWE,Zimbabwe,Lower middle income,Connect/Build,Test,0.18 %,2.465,11.9 %,0.32,...,X,X,X,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,LMIC not receiving partner support,0,LMIC not receiving partner support

In [ ]:
#assessing shape (number of df [rows, columns])
FIND_partner_maps.shape
#confirm that we have the right amount of countries listed --238

(286, 27)

In [ ]:
# Export dataset to .csv
from google.colab import files
FIND_partner_maps.to_csv('FIND_partner_maps.csv') 
files.download('FIND_partner_maps.csv')

Making different datasets to visualize different FIND intervention support, by country and economic class